// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjrwzhnxsrdmxhmhdoyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indqcnd6aG54c3JkbXhobWhkb3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNTExMjgsImV4cCI6MjA3MjcyNzEyOH0.3rMYgpOPCsbIwPLiVp0V7l9aR716W0FpPazeRtXCtTc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});